import SubstrateFramework.Glue
import SubstrateFramework.Ingested.ActionQuantum
import SubstrateFramework.Ingested.AmplitudeCondition
import SubstrateFramework.Ingested.Basin
import SubstrateFramework.Ingested.Bridge
import SubstrateFramework.Ingested.Charge
import SubstrateFramework.Ingested.ChargeDiscrimination
import SubstrateFramework.Ingested.ComparsiVirial
import SubstrateFramework.Ingested.DetectorGeometry
import SubstrateFramework.Ingested.DoubleWell
import SubstrateFramework.Ingested.DrivenNeumannBC
import SubstrateFramework.Ingested.Energy
import SubstrateFramework.Ingested.EnergyFlux
import SubstrateFramework.Ingested.Exchange
import SubstrateFramework.Ingested.Formalization
import SubstrateFramework.Ingested.Gates
import SubstrateFramework.Ingested.HBT_Approach
import SubstrateFramework.Ingested.LandauZener
import SubstrateFramework.Ingested.Phase10CF_Z3CenterConfinement
import SubstrateFramework.Ingested.Phase11Flavor_CPPhaseCount
import SubstrateFramework.Ingested.Phase12GW_LowestMultipole
import SubstrateFramework.Ingested.Phase13FS_HarmonicDoubling
import SubstrateFramework.Ingested.Phase14P3D_SphericalNull
import SubstrateFramework.Ingested.Phase15NC_NonlinearChiralSplit
import SubstrateFramework.Ingested.Phase16QB_TwoPolarizations
import SubstrateFramework.Ingested.Phase17WZW_LevelWinding
import SubstrateFramework.Ingested.Phase18Chiral_GoldstoneCount
import SubstrateFramework.Ingested.Phase19_D3S_LocalityImpliesS1
import SubstrateFramework.Ingested.Phase19_OM1_Z2Character
import SubstrateFramework.Ingested.Phase1Bridge_ThermalGate
import SubstrateFramework.Ingested.Phase20ME_HalfQuantumOrder2
import SubstrateFramework.Ingested.Phase20MH_OverlapHierarchy
import SubstrateFramework.Ingested.Phase21AS_OverDetermination
import SubstrateFramework.Ingested.Phase22AS_BetaPinnedScale
import SubstrateFramework.Ingested.Phase23EW_Sin2ThetaW
import SubstrateFramework.Ingested.Phase25SeedingKernel
import SubstrateFramework.Ingested.Phase26LifetimeKernel
import SubstrateFramework.Ingested.Phase27MediumKernel
import SubstrateFramework.Ingested.Phase28BarrierKernel
import SubstrateFramework.Ingested.Phase29YieldKernel
import SubstrateFramework.Ingested.Phase30PNKernel
import SubstrateFramework.Ingested.Phase31CMKernel
import SubstrateFramework.Ingested.Phase32GBKernel
import SubstrateFramework.Ingested.Phase34KIKernel
import SubstrateFramework.Ingested.Phase37WNKernel
import SubstrateFramework.Ingested.Phase38MDKernel
import SubstrateFramework.Ingested.Phase3EM_U1Current
import SubstrateFramework.Ingested.Phase40TX_RotatingTorus
import SubstrateFramework.Ingested.Phase41GaugeKinetic
import SubstrateFramework.Ingested.Phase46EL_LeptonConstraint
import SubstrateFramework.Ingested.Phase47BM_RigidTopSpectrum
import SubstrateFramework.Ingested.Phase48CE_OperatorAndGap
import SubstrateFramework.Ingested.Phase4Strong_FRSpinStat
import SubstrateFramework.Ingested.Phase5Gravity_GravitonTT
import SubstrateFramework.Ingested.Phase6Weak_MaxParityViolation
import SubstrateFramework.Ingested.Phase7EW_MasslessPhoton
import SubstrateFramework.Ingested.Phase8QCD_SU3GaugeFacts
import SubstrateFramework.Ingested.Phase9SM_AnomalyCancellation
import SubstrateFramework.Ingested.PhaseCondition
import SubstrateFramework.Ingested.ProductionAmplitude
import SubstrateFramework.Ingested.Sigma2Prod

/-!
Historical external Lean corpus ingested from `/home/dan/substrate` (source
commit 6d1f4e0) under the repository's provenance-governed ingestion workflow.

Per-file provenance (source path, source sha256, recorded adaptations, main
theorem): `SubstrateFramework/Ingested/provenance.yaml`.

These are historical machine-checked oracle contributions from the
unified-framework phase ladder, the sine-Gordon breather-ionization project,
and the Comparsi exact-breather run. They are ingested as formal artifacts
with provenance; ingesting them promotes no claim. Theorem statements and
proofs are byte-identical to the sources except for the recorded mechanical
adaptations (namespace wraps, comment rewording, import-path rewrites).
-/
