#!/usr/bin/env python3
"""Independent polar-field and antiderivative review for P014.

This route does not import the proposed U(1)-charge module.
"""

from __future__ import annotations

import sympy as sp

from substrate_framework.verification import CheckLedger


def run() -> int:
    checks = CheckLedger("P014-INDEPENDENT")
    x, t = sp.symbols("x t", real=True)
    radius = sp.Function("R", real=True)(x, t)
    phase = sp.Function("theta", real=True)(x, t)
    field = radius * sp.exp(-sp.I * phase)
    conjugate = radius * sp.exp(sp.I * phase)

    density = sp.simplify(
        sp.I
        * (
            conjugate * sp.diff(field, t)
            - field * sp.diff(conjugate, t)
        )
    )
    covariant_spatial = sp.simplify(
        sp.I
        * (
            conjugate * sp.diff(field, x)
            - field * sp.diff(conjugate, x)
        )
    )
    checks.check(
        "polar decomposition independently gives j_0=2*R^2*theta_t",
        sp.simplify(density - 2 * radius**2 * sp.diff(phase, t)) == 0,
    )
    checks.check(
        "polar decomposition independently gives j_1=2*R^2*theta_x",
        sp.simplify(
            covariant_spatial - 2 * radius**2 * sp.diff(phase, x)
        )
        == 0,
    )

    omega, eta, amplitude = sp.symbols("omega eta A", positive=True)
    stationary_radius = amplitude / sp.cosh(eta * x)
    stationary_density = density.subs(
        {
            radius: stationary_radius,
            sp.diff(phase, t): omega,
        }
    )
    checks.check(
        "the stationary polar field independently gives 2*omega*A^2*sech^2",
        sp.simplify(
            stationary_density
            - 2 * omega * amplitude**2 / sp.cosh(eta * x) ** 2
        )
        == 0,
    )

    antiderivative = sp.tanh(eta * x) / eta
    checks.check(
        "tanh/eta is a direct antiderivative of sech-squared",
        sp.simplify(
            sp.diff(antiderivative, x) - 1 / sp.cosh(eta * x) ** 2
        )
        == 0,
    )
    norm = sp.limit(antiderivative, x, sp.oo) - sp.limit(
        antiderivative, x, -sp.oo
    )
    charge = sp.simplify(2 * omega * amplitude**2 * norm)
    checks.check(
        "endpoint evaluation independently gives Q=4*A^2*omega/eta",
        sp.simplify(charge - 4 * amplitude**2 * omega / eta) == 0,
    )

    energy = 16 * eta
    secant = energy / omega
    checks.check(
        "direct composition independently gives the energy and secant products",
        sp.simplify(charge * energy - 64 * amplitude**2 * omega) == 0
        and sp.simplify(charge * secant - 64 * amplitude**2) == 0,
    )

    rapidity = sp.symbols("rapidity", real=True)
    phase_vector = (
        omega * sp.cosh(rapidity),
        omega * sp.sinh(rapidity),
    )
    energy_momentum = (
        energy * sp.cosh(rapidity),
        energy * sp.sinh(rapidity),
    )
    checks.check(
        "rapidity independently makes the charge-weighted vector relation covariant",
        all(
            sp.simplify(charge * component - 64 * amplitude**2 * phase_component)
            == 0
            for component, phase_component in zip(
                energy_momentum, phase_vector
            )
        ),
    )

    a, b, c, d = sp.symbols("a b c d", integer=True)
    solutions = sp.solve(
        [sp.Eq(a - b + d, 0), sp.Eq(-a + b + c, 0)],
        [c, d],
        dict=True,
    )
    checks.check(
        "elimination independently fixes every invariant exponent vector",
        solutions == [{c: a - b, d: -a + b}],
    )
    general = sp.Matrix([a, b, a - b, b - a])
    generator_one = sp.Matrix([1, 1, 0, 0])
    generator_two = sp.Matrix([1, 0, 1, -1])
    checks.check(
        "every integer solution is generated by Q*H and Q*E/omega",
        sp.simplify(
            general - (b * generator_one + (a - b) * generator_two)
        )
        == sp.zeros(4, 1),
    )

    total = checks.finish()
    print(f"P014 INDEPENDENT REVIEW ALL {total} CHECKS PASS")
    return total


if __name__ == "__main__":
    run()
