"""Fresh exact P240 screen of issue-147's same-order curvature family.

This verifier deliberately does not import or execute the historical P239
enumerator.  It builds every contraction diagram again, converts each into an
exact polynomial, and checks the important methodological bridge: static M5
curvatures generated by symmetric field derivatives have a locally
full-dimensional image in the nine spatial double-two-form coordinates.
"""

from __future__ import annotations

from itertools import combinations, combinations_with_replacement, permutations, product
import json
from pathlib import Path

import sympy as sp

from substrate_framework.m5_covariant_action import m5_curvature_from_derivatives
from substrate_framework.verification import CheckLedger


HERE = Path(__file__).resolve().parent
ETA = sp.ImmutableMatrix(sp.diag(-1, 1, 1, 1))
ETA_DIAGONAL = tuple(ETA[index, index] for index in range(4))
PAIRS = tuple(combinations(range(4), 2))
PAIR_SLOTS = ((0, 1), (2, 3), (4, 5), (6, 7))
FORBIDDEN_SELF_TRACES = {tuple(sorted(pair)) for pair in PAIR_SLOTS}


def perfect_matchings(items: tuple[int, ...]):
    """Yield every unordered perfect matching without duplicate diagrams."""

    if not items:
        yield ()
        return
    first = items[0]
    for position in range(1, len(items)):
        second = items[position]
        remainder = items[1:position] + items[position + 1 :]
        for tail in perfect_matchings(remainder):
            yield ((first, second),) + tail


def all_even_diagrams():
    return tuple(
        matching
        for matching in perfect_matchings(tuple(range(8)))
        if not any(tuple(sorted(pair)) in FORBIDDEN_SELF_TRACES for pair in matching)
    )


def all_one_epsilon_diagrams():
    diagrams = []
    for epsilon_slots in combinations(range(8), 4):
        remainder = tuple(slot for slot in range(8) if slot not in epsilon_slots)
        for matching in perfect_matchings(remainder):
            if any(tuple(sorted(pair)) in FORBIDDEN_SELF_TRACES for pair in matching):
                continue
            diagrams.append((epsilon_slots, matching))
    return tuple(diagrams)


def tensor_from_pair_matrix(matrix: sp.MatrixBase):
    tensor = sp.MutableDenseNDimArray.zeros(4, 4, 4, 4)
    for row, (a, b) in enumerate(PAIRS):
        for column, (c, d) in enumerate(PAIRS):
            value = matrix[row, column]
            tensor[a, b, c, d] = value
            tensor[b, a, c, d] = -value
            tensor[a, b, d, c] = -value
            tensor[b, a, d, c] = value
    return sp.ImmutableDenseNDimArray(tensor)


def evaluate_metric_diagram(curvature, matching) -> sp.Expr:
    total = sp.Integer(0)
    for values in product(range(4), repeat=4):
        indices = [None] * 8
        weight = sp.Integer(1)
        for pair, value in zip(matching, values, strict=True):
            indices[pair[0]] = value
            indices[pair[1]] = value
            weight *= ETA_DIAGONAL[value]
        total += weight * curvature[tuple(indices[:4])] * curvature[tuple(indices[4:])]
    return sp.expand(total)


def permutation_sign(values: tuple[int, ...]) -> int:
    inversions = sum(
        values[left] > values[right]
        for left in range(4)
        for right in range(left + 1, 4)
    )
    return -1 if inversions % 2 else 1


EPSILON_ASSIGNMENTS = tuple(
    (values, permutation_sign(values)) for values in permutations(range(4))
)


def evaluate_one_epsilon_diagram(curvature, diagram) -> sp.Expr:
    epsilon_slots, matching = diagram
    total = sp.Integer(0)
    for epsilon_values, epsilon_sign in EPSILON_ASSIGNMENTS:
        indices = [None] * 8
        for slot, value in zip(epsilon_slots, epsilon_values, strict=True):
            indices[slot] = value
        for values in product(range(4), repeat=2):
            weight = sp.Integer(epsilon_sign)
            for pair, value in zip(matching, values, strict=True):
                indices[pair[0]] = value
                indices[pair[1]] = value
                weight *= ETA_DIAGONAL[value]
            total += weight * curvature[tuple(indices[:4])] * curvature[tuple(indices[4:])]
    return sp.expand(total)


def named_even_invariants(curvature) -> sp.ImmutableMatrix:
    i1 = sum(
        ETA_DIAGONAL[a]
        * ETA_DIAGONAL[b]
        * ETA_DIAGONAL[c]
        * ETA_DIAGONAL[d]
        * curvature[a, b, c, d] ** 2
        for a, b, c, d in product(range(4), repeat=4)
    )
    i2 = sum(
        ETA_DIAGONAL[a]
        * ETA_DIAGONAL[b]
        * ETA_DIAGONAL[c]
        * ETA_DIAGONAL[d]
        * curvature[a, b, c, d]
        * curvature[c, d, a, b]
        for a, b, c, d in product(range(4), repeat=4)
    )
    i3 = sum(
        ETA_DIAGONAL[a]
        * ETA_DIAGONAL[b]
        * ETA_DIAGONAL[c]
        * ETA_DIAGONAL[d]
        * curvature[a, b, c, d]
        * curvature[a, c, b, d]
        for a, b, c, d in product(range(4), repeat=4)
    )
    ricci = sp.Matrix(
        4,
        4,
        lambda a, c: sum(
            ETA_DIAGONAL[b] * curvature[a, b, c, b] for b in range(4)
        ),
    )
    i4 = sum(
        ETA_DIAGONAL[a] * ETA_DIAGONAL[c] * ricci[a, c] ** 2
        for a, c in product(range(4), repeat=2)
    )
    i5 = sum(
        ETA_DIAGONAL[a]
        * ETA_DIAGONAL[c]
        * ricci[a, c]
        * ricci[c, a]
        for a, c in product(range(4), repeat=2)
    )
    scalar = sum(ETA_DIAGONAL[a] * ricci[a, a] for a in range(4))
    return sp.ImmutableMatrix([sp.expand(value) for value in (i1, i2, i3, i4, i5, scalar**2)])


def quadratic_coefficient_matrix(expressions, variables) -> sp.Matrix:
    monomials = tuple(combinations_with_replacement(range(len(variables)), 2))
    rows = []
    for expression in expressions:
        polynomial = sp.Poly(sp.expand(expression), *variables)
        rows.append(
            [
                polynomial.coeff_monomial(variables[left] * variables[right])
                for left, right in monomials
            ]
        )
    return sp.Matrix(rows)


def spatial_source_rank_witness():
    variables = sp.symbols("d0:18")
    derivatives = []
    offset = 0
    for _ in range(3):
        matrix = sp.zeros(3)
        for row in range(3):
            for column in range(row, 3):
                matrix[row, column] = matrix[column, row] = variables[offset]
                offset += 1
        derivatives.append(matrix)

    outputs = []
    for left, right in combinations(range(3), 2):
        commutator = derivatives[left] * derivatives[right] - derivatives[right] * derivatives[left]
        outputs.extend((commutator[0, 1], commutator[0, 2], commutator[1, 2]))
    jacobian = sp.Matrix(outputs).jacobian(variables)
    point_values = (5, 2, 5, 1, 3, -2, -1, 6, 6, -1, -2, 3, 1, 5, 2, 5, 1, 3)
    evaluated = jacobian.subs(dict(zip(variables, point_values, strict=True)))
    pivot_columns = evaluated.rref()[1][:9]
    minor = evaluated[:, pivot_columns].det()
    return evaluated.rank(), pivot_columns, sp.factor(minor), point_values


def source_symmetry_counterexample():
    values = (
        sp.diag(1, 2, 3, 4),
        sp.Matrix([[0, 1, 2, 0], [1, 0, 3, 1], [2, 3, 1, 2], [0, 1, 2, -1]]),
        sp.Matrix([[2, 0, 1, 3], [0, -1, 2, 1], [1, 2, 0, 1], [3, 1, 1, 2]]),
        sp.Matrix([[1, 2, 0, 1], [2, 1, 1, 0], [0, 1, -2, 2], [1, 0, 2, 3]]),
    )
    curvature = m5_curvature_from_derivatives(values)
    pair_exchange_defects = [
        sp.expand(curvature[a, b, c, d] - curvature[c, d, a, b])
        for a, b, c, d in product(range(4), repeat=4)
    ]
    bianchi_defects = [
        sp.expand(curvature[a, b, c, d] + curvature[b, c, a, d] + curvature[c, a, b, d])
        for a, b, c, d in product(range(4), repeat=4)
    ]
    return curvature, pair_exchange_defects, bianchi_defects


def pair_transform(covector_transform: sp.MatrixBase) -> sp.Matrix:
    return sp.Matrix(
        6,
        6,
        lambda new, old: sp.expand(
            covector_transform[PAIRS[old][0], PAIRS[new][0]]
            * covector_transform[PAIRS[old][1], PAIRS[new][1]]
            - covector_transform[PAIRS[old][1], PAIRS[new][0]]
            * covector_transform[PAIRS[old][0], PAIRS[new][1]]
        ),
    )


def transform_tensor(curvature, transformation: sp.MatrixBase):
    matrix = sp.Matrix(
        6,
        6,
        lambda row, column: curvature[
            PAIRS[row][0], PAIRS[row][1], PAIRS[column][0], PAIRS[column][1]
        ],
    )
    induced = pair_transform(transformation.inv())
    return tensor_from_pair_matrix(induced * matrix * induced.T)


def main() -> int:
    ledger = CheckLedger("P240/attempt-0032/source-restricted-quadratic-family")
    even_diagrams = all_even_diagrams()
    odd_diagrams = all_one_epsilon_diagrams()

    generic_variables = sp.symbols("f0:36")
    generic_curvature = tensor_from_pair_matrix(sp.Matrix(6, 6, generic_variables))
    even_expressions = tuple(
        evaluate_metric_diagram(generic_curvature, diagram) for diagram in even_diagrams
    )
    odd_expressions = tuple(
        evaluate_one_epsilon_diagram(generic_curvature, diagram) for diagram in odd_diagrams
    )
    named_even = tuple(named_even_invariants(generic_curvature))
    even_coefficients = quadratic_coefficient_matrix(even_expressions, generic_variables)
    named_even_coefficients = quadratic_coefficient_matrix(named_even, generic_variables)
    odd_coefficients = quadratic_coefficient_matrix(odd_expressions, generic_variables)
    odd_pivots = odd_coefficients.T.rref()[1]

    ledger.check("60 nonzero eta-only diagrams are enumerated", len(even_diagrams) == 60)
    ledger.check("eta-only polynomial space has exact rank six", even_coefficients.rank() == 6)
    ledger.check("six direct named formulas are independent", named_even_coefficients.rank() == 6)
    ledger.check(
        "six direct named formulas span every eta-only diagram",
        sp.Matrix.vstack(named_even_coefficients, even_coefficients).rank() == 6,
    )
    ledger.check("156 nonzero one-epsilon diagrams are enumerated", len(odd_diagrams) == 156)
    ledger.check("one-epsilon polynomial space has exact rank four", odd_coefficients.rank() == 4)
    ledger.check("four one-epsilon pivot polynomials are independent", len(odd_pivots) == 4)

    source_curvature, pair_defects, bianchi_defects = source_symmetry_counterexample()
    ledger.check(
        "canonical source has both within-pair antisymmetries",
        all(
            source_curvature[a, b, c, d] == -source_curvature[b, a, c, d]
            and source_curvature[a, b, c, d] == -source_curvature[a, b, d, c]
            for a, b, c, d in product(range(4), repeat=4)
        ),
    )
    ledger.check("source pair exchange is not an identity", any(value != 0 for value in pair_defects))
    ledger.check("source algebraic Bianchi is not an identity", any(value != 0 for value in bianchi_defects))

    spatial_variables = sp.symbols("s0:9")
    spatial_pair_matrix = sp.zeros(6)
    offset = 0
    for row in (3, 4, 5):
        for column in (3, 4, 5):
            spatial_pair_matrix[row, column] = spatial_variables[offset]
            offset += 1
    spatial_curvature = tensor_from_pair_matrix(spatial_pair_matrix)
    spatial_even = tuple(named_even_invariants(spatial_curvature))
    spatial_coefficients = quadratic_coefficient_matrix(spatial_even, spatial_variables).T
    expected_nullspace = sp.Matrix.hstack(
        sp.Matrix([-sp.Rational(1, 4), -sp.Rational(1, 4), 1, 0, 0, 0]),
        sp.Matrix([sp.Rational(1, 4), -sp.Rational(1, 4), 0, -1, 1, 0]),
        sp.Matrix([1, 0, 0, -4, 0, 1]),
    )
    ledger.check("arbitrary spatial curvature restrictions have exact rank three", spatial_coefficients.rank() == 3)
    ledger.check(
        "displayed three deformations vanish as spatial polynomials",
        spatial_coefficients * expected_nullspace == sp.zeros(spatial_coefficients.rows, 3),
    )
    ledger.check(
        "displayed deformations are the complete spatial polynomial nullspace",
        len(spatial_coefficients.nullspace()) == 3 and expected_nullspace.rank() == 3,
    )
    ledger.check(
        "every one-epsilon diagram vanishes on arbitrary spatial curvature",
        all(evaluate_one_epsilon_diagram(spatial_curvature, diagram) == 0 for diagram in odd_diagrams),
    )

    source_rank, source_pivots, source_minor, source_point = spatial_source_rank_witness()
    ledger.check("symmetric spatial M derivatives reach all nine curvature coordinates locally", source_rank == 9)
    ledger.check("the source-rank certificate has a nonzero exact 9x9 minor", source_minor != 0)

    omega = sp.symbols("omega", real=True)
    derivatives = [sp.diag(omega, 0, 0, 0), sp.zeros(4), sp.zeros(4), sp.zeros(4)]
    derivatives[1][0, 1] = derivatives[1][1, 0] = 1
    clock_curvature = m5_curvature_from_derivatives(tuple(derivatives))
    clock_even = named_even_invariants(clock_curvature)
    ledger.check(
        "affine symmetric-field clock invariant vector is exact",
        clock_even == omega**2 * sp.ImmutableMatrix([4, 4, 2, 2, 2, 4]),
    )
    ledger.check(
        "all static-preserving even deformations vanish on the affine clock",
        clock_even.T * expected_nullspace == sp.zeros(1, 3),
    )
    ledger.check(
        "all one-epsilon deformations vanish on the affine clock",
        all(evaluate_one_epsilon_diagram(clock_curvature, diagram) == 0 for diagram in odd_diagrams),
    )
    baseline_lagrangian = sp.expand(-clock_even[0])
    baseline_hamiltonian = sp.expand(omega * sp.diff(baseline_lagrangian, omega) - baseline_lagrangian)
    ledger.check("preserved baseline clock Hamiltonian is unbounded below", baseline_hamiltonian == -4 * omega**2)

    parity = sp.diag(1, -1, 1, 1)
    parity_curvature = transform_tensor(generic_curvature, parity)
    parity_even = named_even_invariants(parity_curvature)
    ledger.check("improper parity leaves all six even formulas unchanged", parity_even == sp.ImmutableMatrix(named_even))
    ledger.check(
        "improper parity reverses the four independent odd pivots",
        all(
            sp.expand(
                evaluate_one_epsilon_diagram(parity_curvature, odd_diagrams[pivot])
                + odd_expressions[pivot]
            )
            == 0
            for pivot in odd_pivots
        ),
    )

    rational_boost = sp.eye(4)
    rational_boost[0, 0] = rational_boost[1, 1] = sp.Rational(5, 3)
    rational_boost[0, 1] = rational_boost[1, 0] = sp.Rational(4, 3)
    ledger.check("rational boost preserves the mostly-plus metric", rational_boost.T * ETA * rational_boost == ETA)
    boosted = transform_tensor(source_curvature, rational_boost)
    ledger.check(
        "six even representatives are exact proper-Lorentz scalars",
        named_even_invariants(boosted) == named_even_invariants(source_curvature),
    )
    ledger.check(
        "four odd representatives are exact proper-Lorentz scalars",
        all(
            sp.simplify(
                evaluate_one_epsilon_diagram(boosted, odd_diagrams[pivot])
                - evaluate_one_epsilon_diagram(source_curvature, odd_diagrams[pivot])
            )
            == 0
            for pivot in odd_pivots
        ),
    )

    result = {
        "campaign": "P240",
        "attempt": "0032",
        "canonical_goal_issue": "146",
        "candidate_source_issue": "147",
        "candidate": "A_same_order_curvature_contractions",
        "method": "fresh exact polynomial enumeration plus source-map dominance certificate",
        "even_diagram_count": len(even_diagrams),
        "even_rank": even_coefficients.rank(),
        "one_epsilon_diagram_count": len(odd_diagrams),
        "one_epsilon_rank": odd_coefficients.rank(),
        "spatial_even_rank": spatial_coefficients.rank(),
        "spatial_preserving_basis": {
            "N1": "I3-(I1+I2)/4",
            "N2": "(I1-I2)/4-I4+I5",
            "N3": "I1-4*I4+I6",
        },
        "source_static_map": {
            "jacobian_rank": source_rank,
            "pivot_columns": list(source_pivots),
            "minor_determinant": str(source_minor),
            "evaluation_point": list(source_point),
            "interpretation": "nonzero minor proves a locally open source image, so the generic spatial polynomial nullspace is not an over-broad stand-in restriction",
        },
        "clock_witness": {
            "field": "M(t,x)=omega*t*diag(1,0,0,0)+x^1*(E01+E10)",
            "even_invariants": "omega^2*(4,4,2,2,2,4)",
            "all_static_preserving_even_deformations": "0",
            "all_one_epsilon_deformations": "0",
            "hamiltonian_density": "-4*omega^2",
        },
        "verdict": "reject_constant_coefficient_curvature_quadratic_family",
        "verdict_scope": "Exact boundedness failure for the complete constant-coefficient eta/one-epsilon curvature-quadratic family while preserving the full source-generated static 3x3 action. This is not a verdict on field-dependent contractions, higher-order currents, or issue 146.",
        "check_count": len(ledger.passed),
    }
    (HERE / "result.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return ledger.finish()


if __name__ == "__main__":
    raise SystemExit(main())
