"""Canonical, importable definitions and derivations for Substrate."""

from .action_scales import (
    rigid_rotor_energy,
    rigid_rotor_normalized_action,
    secant_action_scale,
)

from .governance import (
    GovernanceError,
    load_yaml,
    render_claim_memory,
    render_claim_index,
    render_release_memory,
    validate_registry,
    validate_release,
)
from .linear_systems import LinearSystemDiagnostics, diagnose_linear_system
from .numerics import (
    BVPEvidence,
    IVPEvidence,
    NumericalFailure,
    RefinementEvidence,
    SolverTolerances,
    refinement_study,
    solve_bvp_evidence,
    solve_ivp_evidence,
    solve_method_of_lines,
)
from .optical_geometry import (
    index_from_potential,
    optical_box_static_1d,
    optical_dilaton,
    optical_dilaton_source_operator_1d,
    optical_metric_1d,
    optical_ricci_scalar_1d,
    slow_geodesic_acceleration_1d,
    slow_geodesic_acceleration_from_potential,
)
from .collective_dynamics import (
    optical_collective_acceleration,
    optical_collective_lagrangian,
    slow_optical_collective_acceleration,
    virial_scaling_exponents,
)
from .constitutive import (
    co_scaled_inverse_permeability,
    co_scaled_permittivity,
    co_scaled_wave_speed,
    lattice_debye_energy,
    lattice_reduced_responses,
    local_wave_speed,
)
from .dimensional_analysis import (
    dimensionless_mass_coordinate,
    dimensionless_group_count,
    dimensionless_monomial_basis,
    mass_from_dimensionless_coordinate,
    mass_coordinate_from_unit_product,
    monomial_exponents,
)
from .radial_energy import (
    capillary_critical_radius,
    capillary_energy,
    line_energy,
    spherical_shell_energy,
)
from .renormalization import (
    one_loop_inverse_coupling_squared,
    one_loop_transmutation_scale,
    single_scale_tension,
    transmuted_mass_coordinate,
)
from .sine_gordon import (
    breather_action,
    breather_action_lattice_adjacent_gap,
    breather_action_lattice_energy,
    breather_action_lattice_frequency,
    breather_action_secant_ratio,
    boosted_breather_energy_momentum,
    boosted_breather_phase_components,
    breather_energy,
    breather_energy_from_action,
    breather_field,
    breather_field_with_width,
    breather_inverse_width,
    breather_frequency_from_action,
    breather_mean_gradient_integral,
    breather_peak_amplitude,
    breather_period,
    breather_secant_action_scale,
    breather_threshold_deficit,
    hamiltonian_density,
    lorentz_factor,
    sine_gordon_residual,
)
from .skyrme_relations import (
    conditional_anw_mass,
    conditional_topological_mass,
    matched_pion_coupling_ratio,
)
from .source_audit import SourceAudit, SourceMatch, audit_source_tokens
from .su3 import (
    SU3Invariants,
    conditional_one_loop_coefficient,
    fundamental_generators,
    invariants,
    structure_constant,
)
from .thermal import (
    symmetric_two_level_gate,
    two_level_occupation_variance,
    two_level_upper_occupation,
)
from .topological_labels import combined_winding_parity, winding_parity
from .u1_charge import (
    breather_charge_energy_product,
    breather_charge_secant_product,
    breather_parameterized_u1_charge,
    charge_scale_exponent_matrix,
    minkowski_dalembertian,
    sech_profile_u1_charge,
    stationary_phase_field,
    stationary_u1_charge_density,
    u1_current_components,
    u1_current_divergence,
)
from .verification import CheckFailure, CheckLedger
from .variational import (
    euler_lagrange_expression,
    solve_euler_lagrange_acceleration,
)

__all__ = [
    "BVPEvidence",
    "GovernanceError",
    "CheckFailure",
    "CheckLedger",
    "IVPEvidence",
    "LinearSystemDiagnostics",
    "NumericalFailure",
    "RefinementEvidence",
    "SolverTolerances",
    "SourceAudit",
    "SourceMatch",
    "SU3Invariants",
    "breather_action",
    "audit_source_tokens",
    "breather_action_lattice_adjacent_gap",
    "breather_action_lattice_energy",
    "breather_action_lattice_frequency",
    "breather_action_secant_ratio",
    "breather_charge_energy_product",
    "breather_charge_secant_product",
    "boosted_breather_energy_momentum",
    "boosted_breather_phase_components",
    "breather_energy",
    "breather_energy_from_action",
    "breather_field",
    "breather_field_with_width",
    "breather_inverse_width",
    "breather_frequency_from_action",
    "breather_mean_gradient_integral",
    "breather_parameterized_u1_charge",
    "breather_peak_amplitude",
    "breather_period",
    "breather_secant_action_scale",
    "breather_threshold_deficit",
    "capillary_critical_radius",
    "capillary_energy",
    "charge_scale_exponent_matrix",
    "co_scaled_inverse_permeability",
    "co_scaled_permittivity",
    "co_scaled_wave_speed",
    "combined_winding_parity",
    "conditional_anw_mass",
    "conditional_one_loop_coefficient",
    "conditional_topological_mass",
    "dimensionless_group_count",
    "dimensionless_mass_coordinate",
    "dimensionless_monomial_basis",
    "diagnose_linear_system",
    "hamiltonian_density",
    "index_from_potential",
    "load_yaml",
    "line_energy",
    "lattice_debye_energy",
    "lattice_reduced_responses",
    "local_wave_speed",
    "lorentz_factor",
    "minkowski_dalembertian",
    "mass_from_dimensionless_coordinate",
    "mass_coordinate_from_unit_product",
    "monomial_exponents",
    "optical_box_static_1d",
    "optical_collective_acceleration",
    "optical_collective_lagrangian",
    "optical_dilaton",
    "optical_dilaton_source_operator_1d",
    "optical_metric_1d",
    "optical_ricci_scalar_1d",
    "one_loop_inverse_coupling_squared",
    "one_loop_transmutation_scale",
    "single_scale_tension",
    "refinement_study",
    "render_claim_memory",
    "render_claim_index",
    "render_release_memory",
    "rigid_rotor_energy",
    "rigid_rotor_normalized_action",
    "secant_action_scale",
    "sech_profile_u1_charge",
    "matched_pion_coupling_ratio",
    "solve_bvp_evidence",
    "solve_ivp_evidence",
    "solve_method_of_lines",
    "stationary_phase_field",
    "stationary_u1_charge_density",
    "slow_geodesic_acceleration_1d",
    "slow_geodesic_acceleration_from_potential",
    "slow_optical_collective_acceleration",
    "spherical_shell_energy",
    "symmetric_two_level_gate",
    "sine_gordon_residual",
    "validate_registry",
    "validate_release",
    "two_level_occupation_variance",
    "two_level_upper_occupation",
    "transmuted_mass_coordinate",
    "u1_current_components",
    "u1_current_divergence",
    "euler_lagrange_expression",
    "fundamental_generators",
    "invariants",
    "solve_euler_lagrange_acceleration",
    "structure_constant",
    "virial_scaling_exponents",
    "winding_parity",
]

__version__ = "0.0.0"
