"""Covariant 3+1 sine-Gordon action and its Euclidean-Hessian fluctuation operator.

This is the Route 1 (induced / Sakharov gravity) rung that follows
``scalar_induced_newton``.  It builds the covariant scalar action whose second
variation is exactly the fluctuation operator that ``scalar_heat_kernel_a2``
already consumes, so a later rung can integrate out the fluctuation without a
new normalization ambiguity.

Declared conventions (mostly-plus signature ``(-,+,+,+)``, matching
``einstein_scalar``):

    S = integral sqrt(-g) [ -(1/2) g^{mu nu} d_mu phi d_nu phi
                            - V(phi) - (1/2) xi R phi^2 ],
    V(phi) = m**2 * (1 - cos phi).

Here ``box_g phi = (1/sqrt(-g)) d_mu( sqrt(-g) g^{mu nu} d_nu phi )`` is the
Laplace-Beltrami operator and ``R`` is the Ricci scalar in the convention
``R_{mu nu} = d_lambda Gamma^lambda_{mu nu} - d_nu Gamma^lambda_{mu lambda}
+ Gamma^lambda_{lambda sigma} Gamma^sigma_{mu nu}
- Gamma^lambda_{nu sigma} Gamma^sigma_{mu lambda}`` (so ``R > 0`` for a sphere
or de Sitter).  In this signature the kinetic term reproduces the accepted
``(phi_t**2 - phi_x**2)/2`` form of ``sine_gordon``.

The Euler-Lagrange field equation generated by this action is

    box_g phi - V'(phi) - xi R phi = 0,

which the constructor verifies against an independent Laplace-Beltrami and
Ricci computation rather than asserting.  Its second variation about a
background ``phi_bg`` is the fluctuation operator

    D phi = ( -box_g + V''(phi_bg) + xi R ) phi,

whose endomorphism ``V''(phi_bg) + xi R`` is exactly the input consumed by
``scalar_induced_newton.scalar_heat_kernel_a2`` under
``D_E = -nabla_E**2 + xi R_E + m**2`` with ``m**2 -> V''(phi_bg)``.  At the
vacuum ``phi_bg = 0``, ``V''(0) = m**2``.

This module supplies a covariant action, its field equation, and its
fluctuation operator only.  It does NOT choose a regulator, identify a cutoff,
integrate out the fluctuation, compute a Newton constant, or make any
observed-gravity comparison; those remain later Route 1 rungs.  It introduces
no fitted constant.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, cast

import sympy as sp
from sympy.calculus.euler import euler_equations

from .exact_symbolic import exact_real as _exact_real
from .exact_symbolic import positive_exact as _positive_exact
from .sine_gordon import sine_gordon_potential

_SPACETIME_DIMENSION = 4


def _coordinates(coordinates: Any) -> tuple[sp.Symbol, ...]:
    coords = tuple(coordinates)
    if len(coords) != _SPACETIME_DIMENSION:
        raise ValueError("coordinates must be four spacetime symbols")
    for coordinate in coords:
        if not isinstance(coordinate, sp.Symbol):
            raise ValueError("each coordinate must be a SymPy Symbol")
    if len(set(coords)) != _SPACETIME_DIMENSION:
        raise ValueError("coordinates must be four distinct symbols")
    return coords


def _metric_matrix(metric: Any) -> sp.Matrix:
    result = sp.Matrix(metric)
    if result.shape != (_SPACETIME_DIMENSION, _SPACETIME_DIMENSION):
        raise ValueError("metric must be a 4 by 4 matrix")
    # Exact-only contract: no floating-point entry may enter this reusable
    # geometry atom, matching the module's exact-symbolic declaration.  A generic
    # coordinate function (e.g. an FLRW scale ``a(t)``) is exact and allowed; a
    # ``Float`` such as ``-1.0`` is not (it is the ``diag(-1.0, 1, 1, 1)``
    # counterexample this contract now rejects).
    if result.has(sp.Float):
        raise ValueError("metric entries must be exact rather than floating")
    if sp.simplify(result - result.T) != sp.zeros(_SPACETIME_DIMENSION):
        raise ValueError("metric must be symmetric")
    # Mostly-plus Lorentzian premise.  For a DECIDABLE (constant, no free symbol)
    # metric the signature must be exactly (-,+,+,+): one negative and three
    # positive eigenvalues.  This rejects a Euclidean ``eye(4)`` (whose
    # ``sqrt(-det g)`` would be the imaginary ``I``) and any other decidably
    # non-Lorentzian or degenerate constant metric.  A coordinate-dependent
    # metric cannot be decided symbolically, so its mostly-plus signature is the
    # caller's documented premise and is not rejected here.
    if not result.free_symbols:
        eigenvalues = cast("dict[sp.Expr, int]", result.eigenvals())
        negative = sum(mult for value, mult in eigenvalues.items() if value.is_negative)
        positive = sum(mult for value, mult in eigenvalues.items() if value.is_positive)
        if negative != 1 or positive != _SPACETIME_DIMENSION - 1:
            raise ValueError(
                "constant metric must have mostly-plus Lorentzian signature (-,+,+,+)"
            )
    return result


def _applied_field(field: Any, coordinates: tuple[sp.Symbol, ...]) -> sp.Expr:
    expression = sp.sympify(field)
    functions = expression.atoms(sp.Function)
    if len(functions) != 1:
        raise ValueError("field must be exactly one applied scalar function")
    (applied,) = functions
    field_arguments = set(applied.args)
    if not field_arguments:
        raise ValueError("field must depend on at least one coordinate")
    if not field_arguments.issubset(set(coordinates)):
        raise ValueError("field may depend only on the given coordinates")
    return expression


def metric_determinant(metric: Any) -> sp.Expr:
    """Return the exact determinant of a declared 4 by 4 metric."""

    return sp.simplify(_metric_matrix(metric).det())


def sqrt_minus_g(metric: Any) -> sp.Expr:
    """Return ``sqrt(-det g)`` for a Lorentzian metric."""

    return sp.sqrt(-metric_determinant(metric))


def inverse_metric(metric: Any) -> sp.Matrix:
    """Return the exact inverse of an invertible 4 by 4 metric."""

    result = _metric_matrix(metric)
    if sp.simplify(result.det()) == 0:
        raise ValueError("metric must be invertible")
    return result.inv().applyfunc(sp.simplify)


def laplace_beltrami(field: Any, metric: Any, coordinates: Any) -> sp.Expr:
    r"""Return ``(1/sqrt(-g)) d_mu( sqrt(-g) g^{mu nu} d_nu field )``."""

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    inverse = inverse_metric(metric_matrix)
    root = sqrt_minus_g(metric_matrix)
    divergence = sp.Integer(0)
    for mu in range(_SPACETIME_DIMENSION):
        flux = sp.Integer(0)
        for nu in range(_SPACETIME_DIMENSION):
            flux += inverse[mu, nu] * sp.diff(field, coords[nu])
        divergence += sp.diff(root * flux, coords[mu])
    return sp.simplify(divergence / root)


def christoffel_symbols(metric: Any, coordinates: Any) -> list[list[list[sp.Expr]]]:
    r"""Return ``Gamma[l][mu][nu] = (1/2) g^{l s}(d_mu g_{nu s}+d_nu g_{mu s}-d_s g_{mu nu})``."""

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    inverse = inverse_metric(metric_matrix)
    dimension = _SPACETIME_DIMENSION
    gamma = [
        [[sp.Integer(0) for _ in range(dimension)] for _ in range(dimension)]
        for _ in range(dimension)
    ]
    for upper in range(dimension):
        for mu in range(dimension):
            for nu in range(dimension):
                total = sp.Integer(0)
                for sigma in range(dimension):
                    total += inverse[upper, sigma] * (
                        sp.diff(metric_matrix[nu, sigma], coords[mu])
                        + sp.diff(metric_matrix[mu, sigma], coords[nu])
                        - sp.diff(metric_matrix[mu, nu], coords[sigma])
                    )
                gamma[upper][mu][nu] = sp.simplify(total / 2)
    return gamma


def ricci_tensor(metric: Any, coordinates: Any) -> sp.Matrix:
    """Return the exact Ricci tensor in the declared convention."""

    coords = _coordinates(coordinates)
    gamma = christoffel_symbols(metric, coords)
    dimension = _SPACETIME_DIMENSION
    tensor = sp.zeros(dimension, dimension)
    for mu in range(dimension):
        for nu in range(dimension):
            entry = sp.Integer(0)
            for upper in range(dimension):
                entry += sp.diff(gamma[upper][mu][nu], coords[upper])
                entry -= sp.diff(gamma[upper][mu][upper], coords[nu])
                for sigma in range(dimension):
                    entry += gamma[upper][upper][sigma] * gamma[sigma][mu][nu]
                    entry -= gamma[upper][nu][sigma] * gamma[sigma][mu][upper]
            tensor[mu, nu] = sp.simplify(entry)
    return tensor


def ricci_scalar(metric: Any, coordinates: Any) -> sp.Expr:
    """Return ``R = g^{mu nu} R_{mu nu}`` for a declared metric."""

    metric_matrix = _metric_matrix(metric)
    inverse = inverse_metric(metric_matrix)
    tensor = ricci_tensor(metric_matrix, coordinates)
    dimension = _SPACETIME_DIMENSION
    scalar = sp.Integer(0)
    for mu in range(dimension):
        for nu in range(dimension):
            scalar += inverse[mu, nu] * tensor[mu, nu]
    return sp.simplify(scalar)


def sine_gordon_potential_scaled(field: Any, mass_squared: Any = 1) -> sp.Expr:
    """Return ``m**2 * (1 - cos phi)`` composed from the accepted potential."""

    mass = _positive_exact(mass_squared, "mass_squared")
    return sp.simplify(mass * sine_gordon_potential(field))


@dataclass(frozen=True)
class CovariantSineGordonFluctuation:
    """Second-variation (Euclidean-Hessian) data about a background."""

    background: sp.Expr
    non_minimal_coupling: sp.Expr
    mass_squared: sp.Expr
    potential_second_derivative: sp.Expr
    curvature_endomorphism: sp.Expr
    endomorphism: sp.Expr
    vacuum_mass_squared: sp.Expr


@dataclass(frozen=True)
class CovariantSineGordonAction:
    """Covariant action ledger with a verified Euler-Lagrange field equation."""

    coordinates: tuple[sp.Symbol, ...]
    metric: sp.Matrix
    sqrt_minus_g: sp.Expr
    ricci_scalar: sp.Expr
    non_minimal_coupling: sp.Expr
    mass_squared: sp.Expr
    potential: sp.Expr
    action_density: sp.Expr
    euler_lagrange: sp.Expr
    field_equation: sp.Expr
    fluctuation: CovariantSineGordonFluctuation


def covariant_sine_gordon_action_density(
    field: Any,
    metric: Any,
    coordinates: Any,
    *,
    non_minimal_coupling: Any = 0,
    mass_squared: Any = 1,
    measure: sp.Expr | None = None,
    curvature_sign: int = 1,
) -> sp.Expr:
    r"""Return the Lagrangian density ``measure * L`` of the covariant action.

    The canonical measure is ``sqrt(-g)``.  ``measure`` and ``curvature_sign``
    exist only so a caller can build a deliberately wrong control (a mutated
    measure or a flipped non-minimal-coupling sign); the physical construction
    uses the defaults.
    """

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    inverse = inverse_metric(metric_matrix)
    xi = _exact_real(non_minimal_coupling, "non_minimal_coupling")
    if curvature_sign not in (1, -1):
        raise ValueError("curvature_sign must be exactly 1 or -1")
    root = sqrt_minus_g(metric_matrix) if measure is None else sp.sympify(measure)
    scalar_curvature = ricci_scalar(metric_matrix, coords)

    kinetic = sp.Integer(0)
    for mu in range(_SPACETIME_DIMENSION):
        for nu in range(_SPACETIME_DIMENSION):
            kinetic += (
                inverse[mu, nu]
                * sp.diff(field, coords[mu])
                * sp.diff(field, coords[nu])
            )
    potential = sine_gordon_potential_scaled(field, mass_squared)
    lagrangian = (
        -kinetic / 2
        - potential
        - curvature_sign * xi * scalar_curvature * field**2 / 2
    )
    return sp.simplify(root * lagrangian)


def covariant_sine_gordon_field_equation(
    field: Any,
    metric: Any,
    coordinates: Any,
    *,
    non_minimal_coupling: Any = 0,
    mass_squared: Any = 1,
) -> sp.Expr:
    r"""Return the covariant EOM residual ``box_g phi - V'(phi) - xi R phi``."""

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    xi = _exact_real(non_minimal_coupling, "non_minimal_coupling")
    mass = _positive_exact(mass_squared, "mass_squared")
    box = laplace_beltrami(field, metric_matrix, coords)
    potential_prime = mass * sp.sin(field)
    scalar_curvature = ricci_scalar(metric_matrix, coords)
    return sp.simplify(box - potential_prime - xi * scalar_curvature * field)


def covariant_sine_gordon_fluctuation_operator(
    background: Any,
    metric: Any,
    coordinates: Any,
    *,
    non_minimal_coupling: Any = 0,
    mass_squared: Any = 1,
) -> CovariantSineGordonFluctuation:
    r"""Return the endomorphism ``V''(phi_bg) + xi R`` of ``D = -box_g + E``.

    This is the operator whose Euclidean form is
    ``D_E = -nabla_E**2 + xi R_E + m**2`` with ``m**2 -> V''(phi_bg)``; at the
    vacuum ``phi_bg = 0`` the mass term is ``V''(0) = m**2``.
    """

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    xi = _exact_real(non_minimal_coupling, "non_minimal_coupling")
    mass = _positive_exact(mass_squared, "mass_squared")
    background_expr = sp.sympify(background)
    potential_second = sp.simplify(mass * sp.cos(background_expr))
    scalar_curvature = ricci_scalar(metric_matrix, coords)
    curvature_endomorphism = sp.simplify(xi * scalar_curvature)
    endomorphism = sp.simplify(potential_second + curvature_endomorphism)
    return CovariantSineGordonFluctuation(
        background=background_expr,
        non_minimal_coupling=xi,
        mass_squared=mass,
        potential_second_derivative=potential_second,
        curvature_endomorphism=curvature_endomorphism,
        endomorphism=endomorphism,
        vacuum_mass_squared=mass,
    )


def covariant_sine_gordon_action(
    field: Any,
    metric: Any,
    coordinates: Any,
    *,
    non_minimal_coupling: Any = 0,
    mass_squared: Any = 1,
    background: Any = 0,
) -> CovariantSineGordonAction:
    r"""Return the covariant action ledger with a verified field equation.

    The constructor derives the Euler-Lagrange expression of the ``sqrt(-g)``
    action and requires it to equal ``sqrt(-g) * (box_g phi - V'(phi)
    - xi R phi)``, so the returned field equation is proven by the action
    rather than asserted.  ``field`` must be one applied scalar function of the
    four coordinates.
    """

    coords = _coordinates(coordinates)
    metric_matrix = _metric_matrix(metric)
    applied_field = _applied_field(field, coords)
    xi = _exact_real(non_minimal_coupling, "non_minimal_coupling")
    mass = _positive_exact(mass_squared, "mass_squared")

    root = sqrt_minus_g(metric_matrix)
    scalar_curvature = ricci_scalar(metric_matrix, coords)
    potential = sine_gordon_potential_scaled(applied_field, mass)
    density = covariant_sine_gordon_action_density(
        applied_field,
        metric_matrix,
        coords,
        non_minimal_coupling=xi,
        mass_squared=mass,
    )
    residual = covariant_sine_gordon_field_equation(
        applied_field,
        metric_matrix,
        coords,
        non_minimal_coupling=xi,
        mass_squared=mass,
    )

    (applied,) = applied_field.atoms(sp.Function)
    field_variables = [coordinate for coordinate in coords if coordinate in applied.args]
    euler = euler_equations(density, [applied_field], field_variables)
    if len(euler) != 1:
        raise AssertionError("covariant sine-Gordon action must yield one field equation")
    euler_lhs = sp.simplify(euler[0].lhs - euler[0].rhs)
    if sp.simplify(euler_lhs - root * residual) != 0:
        raise AssertionError(
            "Euler-Lagrange expression does not equal sqrt(-g)*(box phi - V' - xi R phi)"
        )

    fluctuation = covariant_sine_gordon_fluctuation_operator(
        background,
        metric_matrix,
        coords,
        non_minimal_coupling=xi,
        mass_squared=mass,
    )

    return CovariantSineGordonAction(
        coordinates=coords,
        metric=metric_matrix,
        sqrt_minus_g=root,
        ricci_scalar=scalar_curvature,
        non_minimal_coupling=xi,
        mass_squared=mass,
        potential=potential,
        action_density=density,
        euler_lagrange=euler_lhs,
        field_equation=residual,
        fluctuation=fluctuation,
    )
