"""Exact conditional ledgers for two-length one-loop scale maps.

These functions compose dimension-matrix, one-loop, inverse-energy length, and
log-identifiability algebra.  They do not identify either energy with QCD, a
lattice, a soliton, or a hadron; derive the beta function, coupling, conversion
constant, or absolute scale; or establish perturbative control at the formal
transmutation scale.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import sympy as sp

from .dimensional_analysis import (
    dimensionless_group_count,
    dimensionless_monomial_basis,
)
from .renormalization import one_loop_transmutation_scale
from .scale_constraints import LogConstraintDiagnostics, diagnose_log_constraints


def _positive(value: Any, name: str) -> sp.Expr:
    expression = sp.sympify(value)
    if expression.is_number and expression.is_positive is not True:
        raise ValueError(f"{name} must be positive")
    return expression


@dataclass(frozen=True)
class TwoLengthDimensionLedger:
    """Dimension matrix and kernel for two lengths and one speed."""

    dimension_matrix: sp.ImmutableMatrix
    rank: int
    dimensionless_group_count: int
    monomial_kernel: tuple[sp.ImmutableMatrix, ...]


@dataclass(frozen=True)
class OneLoopLengthRatioLedger:
    """A conditional one-loop energy ratio and inverse-energy length map."""

    reference_energy: sp.Expr
    coupling_squared: sp.Expr
    beta_coefficient: sp.Expr
    reference_conversion: sp.Expr
    transmuted_conversion: sp.Expr
    exponent: sp.Expr
    transmuted_energy: sp.Expr
    transmuted_to_reference_energy_ratio: sp.Expr
    reference_length: sp.Expr
    transmuted_length: sp.Expr
    transmuted_to_reference_length_ratio: sp.Expr
    reference_to_transmuted_length_ratio: sp.Expr
    inferred_coupling_squared: sp.Expr


def two_length_speed_dimension_ledger() -> TwoLengthDimensionLedger:
    """Return the canonical ``(L,T)`` rows for ``(ell0,ell1,c)`` columns.

    The matrix is ``[[1,1,1],[0,0,-1]]``.  Its one-dimensional kernel is
    generated by ``(-1,1,0)``, representing ``ell1/ell0``.  The opposite
    generator represents the reciprocal and is equally valid; dimensional
    analysis selects neither orientation nor a value for the ratio.
    """

    matrix = sp.Matrix([[1, 1, 1], [0, 0, -1]])
    kernel = dimensionless_monomial_basis(matrix)
    return TwoLengthDimensionLedger(
        dimension_matrix=sp.ImmutableMatrix(matrix),
        rank=int(matrix.rank()),
        dimensionless_group_count=dimensionless_group_count(matrix),
        monomial_kernel=tuple(sp.ImmutableMatrix(vector) for vector in kernel),
    )


def one_loop_inverse_energy_length_ledger(
    reference_energy: Any,
    coupling_squared: Any,
    beta_coefficient: Any,
    *,
    reference_conversion: Any = 1,
    transmuted_conversion: Any = 1,
) -> OneLoopLengthRatioLedger:
    """Compose a formal one-loop scale with ``ell=K/E`` exactly.

    For positive inputs, let ``X=8*pi**2/(b0*g2)`` and
    ``Lambda=mu0*exp(-X)``.  With independently supplied positive conversion
    constants ``K0`` and ``K1``, define ``ell0=K0/mu0`` and
    ``ell1=K1/Lambda``.  Then

    ``ell1/ell0=(K1/K0)*exp(X)``.

    Only when ``K1=K0`` is the length ratio exactly the inverse energy ratio.
    The displayed inverse ``g2=8*pi**2/(b0*log((ell1/ell0)/(K1/K0)))`` requires
    the supplied length ratio to exceed ``K1/K0``; it infers a free input from
    a supplied ratio and is not a parameter-free prediction.
    """

    mu0 = _positive(reference_energy, "reference_energy")
    g2 = _positive(coupling_squared, "coupling_squared")
    b0 = _positive(beta_coefficient, "beta_coefficient")
    conversion0 = _positive(reference_conversion, "reference_conversion")
    conversion1 = _positive(transmuted_conversion, "transmuted_conversion")
    exponent = sp.simplify(8 * sp.pi**2 / (b0 * g2))
    transmuted = one_loop_transmutation_scale(mu0, sp.sqrt(g2), b0)
    energy_ratio = sp.simplify(transmuted / mu0)
    length0 = sp.simplify(conversion0 / mu0)
    length1 = sp.simplify(conversion1 / transmuted)
    length_ratio = sp.simplify(length1 / length0)
    conversion_ratio = sp.simplify(conversion1 / conversion0)
    inferred = sp.simplify(
        8 * sp.pi**2 / (b0 * sp.log(length_ratio / conversion_ratio))
    )
    return OneLoopLengthRatioLedger(
        reference_energy=mu0,
        coupling_squared=g2,
        beta_coefficient=b0,
        reference_conversion=conversion0,
        transmuted_conversion=conversion1,
        exponent=exponent,
        transmuted_energy=transmuted,
        transmuted_to_reference_energy_ratio=energy_ratio,
        reference_length=length0,
        transmuted_length=length1,
        transmuted_to_reference_length_ratio=length_ratio,
        reference_to_transmuted_length_ratio=sp.simplify(1 / length_ratio),
        inferred_coupling_squared=inferred,
    )


def coupling_squared_from_length_ratio(
    length_ratio: Any,
    beta_coefficient: Any,
    *,
    conversion_ratio: Any = 1,
) -> sp.Expr:
    """Infer the conditional positive coupling squared from a supplied ratio.

    The ratio means ``ell_transmuted/ell_reference`` and must exceed the
    positive conversion-prefactor ratio.  For symbolic inputs the caller must
    supply or separately prove this strict inequality; decidably false numeric
    inputs are rejected.
    """

    ratio = _positive(length_ratio, "length_ratio")
    b0 = _positive(beta_coefficient, "beta_coefficient")
    prefactor = _positive(conversion_ratio, "conversion_ratio")
    reduced_ratio = sp.simplify(ratio / prefactor)
    if reduced_ratio.is_number and bool(reduced_ratio <= 1):
        raise ValueError("length_ratio must exceed conversion_ratio")
    return sp.simplify(8 * sp.pi**2 / (b0 * sp.log(reduced_ratio)))


def two_length_log_constraint(
    transmuted_to_reference_ratio: Any,
    *,
    provenance: str,
) -> LogConstraintDiagnostics:
    """Return one exact row on ``(log ell0, log ell1)``.

    The equation is ``-log(ell0)+log(ell1)=log(ratio)``.  Its nullspace is the
    common-rescaling direction ``(1,1)``.  Thus the ratio is fixed
    conditionally while neither absolute log length is identifiable.
    """

    ratio = _positive(
        transmuted_to_reference_ratio,
        "transmuted_to_reference_ratio",
    )
    if not isinstance(provenance, str) or not provenance.strip():
        raise ValueError("provenance must be a non-empty string")
    return diagnose_log_constraints(
        [[-1, 1]],
        [sp.log(ratio)],
        provenance=[provenance],
    )


def common_length_rescaling(
    reference_length: Any,
    transmuted_length: Any,
    factor: Any,
) -> tuple[sp.Expr, sp.Expr, sp.Expr]:
    """Rescale both positive lengths and return their unchanged ratio."""

    length0 = _positive(reference_length, "reference_length")
    length1 = _positive(transmuted_length, "transmuted_length")
    rho = _positive(factor, "factor")
    return (
        sp.simplify(rho * length0),
        sp.simplify(rho * length1),
        sp.simplify(length1 / length0),
    )
