#!/usr/bin/env python3
"""Independent exact rederivation of the O1 topology and Berry boundary."""

from __future__ import annotations

import sympy as sp

from substrate_framework.verification import CheckLedger


def _zero(value: object) -> bool:
    if isinstance(value, sp.MatrixBase):
        return all(sp.simplify(entry) == 0 for entry in value)
    return sp.simplify(value) == 0


def _berry(section: sp.Matrix, coordinate: sp.Symbol) -> tuple[sp.Expr, ...]:
    projector = sp.simplify(section * section.H)
    start = section.subs(coordinate, 0)
    end = section.subs(coordinate, 2 * sp.pi)
    transition = sp.simplify((start.H * end)[0])
    connection = sp.simplify(sp.I * (section.H * sp.diff(section, coordinate))[0])
    integral = sp.simplify(sp.integrate(connection, (coordinate, 0, 2 * sp.pi)))
    bare = sp.simplify(sp.exp(sp.I * integral))
    return projector, transition, connection, integral, bare, sp.simplify(transition * bare)


def run() -> int:
    checks = CheckLedger("P157-independent")
    phi = sp.Symbol("phi", real=True)
    root_two = sp.sqrt(2)
    f_x = sp.Matrix([[0, 1, 0], [1, 0, 1], [0, 1, 0]]) / root_two
    f_y = sp.Matrix([[0, -sp.I, 0], [sp.I, 0, -sp.I], [0, sp.I, 0]]) / root_two
    f_z = sp.diag(1, 0, -1)
    reference = sp.Matrix([0, 1, 0])
    checks.check(
        "reference is normalized and unmagnetized",
        (reference.H * reference)[0] == 1
        and all((reference.H * matrix * reference)[0] == 0 for matrix in (f_x, f_y, f_z)),
    )
    y_flip = sp.simplify((-sp.I * sp.pi * f_y).exp() * reference)
    checks.check(
        "perpendicular pi rotation flips the spinor but not its projector",
        y_flip == -reference and _zero(y_flip * y_flip.H - reference * reference.H),
    )

    r_z = sp.simplify((-sp.I * phi * f_z).exp())
    fixed_section = sp.simplify(sp.exp(sp.I * phi / 2) * r_z * reference)
    fixed = _berry(fixed_section, phi)
    checks.check(
        "O1 rotation fixes the reference ray",
        r_z * reference == reference
        and _zero(sp.diff(fixed[0], phi)),
    )
    checks.check(
        "fixed-ray local integral is minus pi",
        fixed[2] == -sp.Rational(1, 2)
        and fixed[3] == -sp.pi
        and fixed[4] == -1,
    )
    checks.check(
        "fixed-ray endpoint cancels the bare phase",
        fixed[1] == -1 and fixed[5] == 1,
    )
    opposite = _berry(sp.exp(-sp.I * phi / 2) * reference, phi)
    checks.check(
        "opposite local convention leaves corrected fixed-ray answer unchanged",
        opposite[0] == fixed[0]
        and opposite[2] == sp.Rational(1, 2)
        and opposite[5] == fixed[5] == 1,
    )

    director = sp.Matrix([sp.cos(phi / 2), sp.sin(phi / 2), 0])
    director_spinor = sp.Matrix(
        [
            -(director[0] - sp.I * director[1]) / root_two,
            director[2],
            (director[0] + sp.I * director[1]) / root_two,
        ]
    )
    real_lift = _berry(director_spinor, phi)
    checks.check(
        "director spinor is normalized and unmagnetized",
        sp.simplify((director_spinor.H * director_spinor)[0]) == 1
        and all(
            sp.simplify((director_spinor.H * matrix * director_spinor)[0]) == 0
            for matrix in (f_x, f_y, f_z)
        ),
    )
    checks.check(
        "director half turn closes only as a ray",
        director.subs(phi, 2 * sp.pi) == -director.subs(phi, 0)
        and director_spinor.subs(phi, 2 * sp.pi) == -director_spinor.subs(phi, 0)
        and not _zero(sp.diff(real_lift[0], phi)),
    )
    checks.check(
        "real director lift has endpoint-carried minus-one holonomy",
        real_lift[1] == -1
        and real_lift[2] == 0
        and real_lift[4] == 1
        and real_lift[5] == -1,
    )
    periodic = _berry(sp.exp(-sp.I * phi / 2) * director_spinor, phi)
    checks.check(
        "periodic director gauge has integral-carried minus-one holonomy",
        periodic[1] == 1
        and periodic[2] == sp.Rational(1, 2)
        and periodic[4] == periodic[5] == -1,
    )
    full_polar = _berry(sp.exp(sp.I * phi / 2) * director_spinor, phi)
    checks.check(
        "combined half phase and director path closes in the full polar quotient",
        full_polar[1] == 1
        and full_polar[2] == -sp.Rational(1, 2)
        and full_polar[5] == -1,
    )

    spin_one_2pi = sp.simplify((-sp.I * 2 * sp.pi * f_z).exp())
    fundamental_z = sp.diag(sp.Rational(1, 2), -sp.Rational(1, 2))
    fundamental_2pi = sp.simplify((-sp.I * 2 * sp.pi * fundamental_z).exp())
    checks.check(
        "integer and half-integer carriers see the center differently",
        spin_one_2pi == sp.eye(3) and fundamental_2pi == -sp.eye(2),
    )
    checks.check(
        "inserted half phase is not generated by spin-one rotation",
        fixed_section.subs(phi, 2 * sp.pi) == -fixed_section.subs(phi, 0)
        and spin_one_2pi * reference == reference,
    )

    director_signs = tuple((-1) ** step for step in range(4))
    phase_shifts = tuple(step * sp.pi for step in range(4))
    checks.check(
        "full polar deck sequence is infinite rather than order two",
        director_signs == (1, -1, 1, -1)
        and phase_shifts == (0, sp.pi, 2 * sp.pi, 3 * sp.pi)
        and phase_shifts[2] != phase_shifts[0],
    )
    scalar_integer = sp.exp(sp.I * phi)
    scalar_half = sp.exp(sp.I * phi / 2)
    checks.check(
        "scalar U1 closure distinguishes integer from half winding",
        scalar_integer.subs(phi, 2 * sp.pi) == scalar_integer.subs(phi, 0)
        and scalar_half.subs(phi, 2 * sp.pi) != scalar_half.subs(phi, 0),
    )
    dictionaries = {
        "director_ray": real_lift[5],
        "fundamental_center": fundamental_2pi[0, 0],
        "parity_character": sp.Integer(-1),
    }
    checks.check(
        "equal scalar values do not identify their domains",
        len(set(dictionaries)) == 3
        and all(value == -1 for value in dictionaries.values()),
    )
    checks.check(
        "projector mutation separates O1 from the genuine director loop",
        _zero(sp.diff(fixed[0], phi))
        and not _zero(sp.diff(real_lift[0], phi))
        and fixed[5] != real_lift[5],
    )
    return checks.finish()


if __name__ == "__main__":
    tally = run()
    print(f"P157 INDEPENDENT ALL {tally} CHECKS PASS")
